using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Uhuru.Prison.Data
{
    /// <summary>
    /// This is a partial implementation of the PrisonEntities class that is auto-generated by the EntityFramework.
    /// </summary>
    public partial class PrisonEntities
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrisonEntities"/> class.
        /// We need this constructor in order to programatically connect to a database, without the need for a configuration file.
        /// </summary>
        /// <param name="connectionstring">The connectionstring.</param>
        public PrisonEntities(string connectionstring)
            : base(connectionstring)
        {
        }
    }
}